/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDatatable: typeof import('./components/TheDatatable.vue')['default']
    TicketsDatatable: typeof import('./components/TicketsDatatable.vue')['default']
    TicketsDataTable: typeof import('./components/TicketsDataTable.vue')['default']
    TicketsDatatableFilters: typeof import('./components/TicketsDatatableFilters.vue')['default']
    TicketsDataTableFilters: typeof import('./components/TicketsDataTableFilters.vue')['default']
    TicketTable: typeof import('./components/TicketTable.vue')['default']
    TicketTableCell: typeof import('./components/TicketTableCell.vue')['default']
    TicketTableCellDate: typeof import('./components/TicketTableCellDate.vue')['default']
  }
}
